### PR TITLE
Add first pass protocol docs

### PR DESCRIPTION
**Pull request by carrion256**
This change is [Reviewable](https://reviewable.io/reviews/Nuffle-Labs/docs/4)

## Summary by CodeRabbit

- **New Features**
  - Introduced the Nuff Protocol documentation, detailing a framework for threshold signatures and application execution in decentralised environments.
  - Emphasised the HARTS threshold signature scheme for robust performance and security.
  - Included an ERC-4337 aware adaptor contract for enhanced compatibility with Ethereum and non-EVM chains.
  - Detailed the application execution flow, including registration and validation processes.
  - Highlighted a trust-minimised slashing mechanism for secure asset representation across chains.
  - Discussed storage requirements, advocating for a decentralised and immutable solution to maintain protocol integrity.

### CODE REVIEW

**Review by palozano — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Nuffle-Labs/docs/4)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @dndll and @firatsertgoz)

___
*[`protocol.md` line 9 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5Hz6q41L4UNUaBTLMb:-O5Hz6q41L4UNUaBTLMc:bs751p6) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L9)):*
> ```Markdown
> The Nuff Protocol leverages the current state-of-the-art threshold signature protocol[^harts]. 
> 
> the following properties that enable the Nuff Protocol:
> ```

I know this will have more eyes reviewing it, but I will leave some suggestions regarding wording/phrasing, if it's okay. Feel free to resolve or ignore.

Should this be "The following properties enable the Nuff Protocol:"?
___
*[`protocol.md` line 14 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I-1MQAW-PKyR-3xlI:-O5I-1MQAW-PKyR-3xlJ:bq649zt) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L14)):*
> ```Markdown
> - Efficient: HARTS outputs a Schnorr signature of size $\lambda$ with a near-optimal amortized communication cost of $O\left(\lambda n^{2} \log n\right)$ bits and $O(1)$ rounds per signature. This means that dealing shares is amortized and that the signing round is constant. The arrangement of nonce shares happen offline once retrieved.
> - Robustness: HARTS ensures guaranteed output delivery, even in asynchronous conditions.
> - Internal agreement protocol: HARTS internally uses a VABA to agree on the dealers of the system. We can extend this VABA to agree on the message to be signed to protect the assets further.
> ```

VABA *Protocol*
___
*[`protocol.md` line 25 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I-UrBEeCdp8rnUGEr:-O5I-UrBEeCdp8rnUGEs:b-ycpd9u) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L25)):*
> ```Markdown
> ### Adapter 
> 
> The signing protocol outputs a schnorr signature, for this reason it is not compatible all underlying chains natively. 
> ```

Schnorr (with capital letter), "...compatible *with* all..."
___
*[`protocol.md` line 147 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I2NNw5Zi1VGHKSS-G:-O5I2NNw5Zi1VGHKSS-H:b-a4tl48) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L147)):*
> ```Markdown
>     - The protocol initiates a dealing 
>     - Sources an operator set, or instructs guardians to support the application. Here we omit guardian details for later discussion.
>     - Initiates a deployment of a contract (this might change if 1: or 1:1)
> ```

Is there something missing after the first `1:`?
___
*[`protocol.md` line 150 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I2ZGt8oXiqhq0WVh_:-O5I2ZGt8oXiqhq0WVha:b-5l9twm) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L150)):*
> ```Markdown
> - If the shard is not new: 
>     - The protocol allocates the application to the shard.
> - Based on the allocated shard, the protocol signs a registers transaction and registers as an operator with the restaking platforms for the application.
> ```

the first `registers` is a typo?

**Comment by carrion256** [comment]
*[`protocol.md` line 9 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5NRVp0EZR0FUxr0pL8:-O5NRVp0EZR0FUxr0pL9:b-s3u245) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L9)):*
> ```Markdown
> The Nuff Protocol leverages the current state-of-the-art threshold signature protocol[^harts]. 
> 
> the following properties that enable the Nuff Protocol:
> ```

The following properties enable the Nuff Protocol:



_Code quote:_
```Markdown
the following properties that enable the Nuff Protocol:
```

**Comment by carrion256** [comment]
*[`protocol.md` line 9 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5NS4Uf8lJ5SeYAtvCe:-O5NS4Uf8lJ5SeYAtvCf:undefined) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L9)):*
> ```Markdown
> The Nuff Protocol leverages the current state-of-the-art threshold signature protocol[^harts]. 
> 
> the following properties that enable the Nuff Protocol:
> ```





_Code quote (i):_
```Markdown
the following properties that enable the Nuff Protocol:
```



_Code snippet (ii):_
```Markdown
The following properties enable the Nuff Protocol:
```

**Comment by carrion256** [comment]
*[`protocol.md` line 14 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I-1MQAW-PKyR-3xlI:-O5NSKywB3pRJKgk7GPb:b8u64dv) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L14)):*
<details><summary><i>Previously, palozano (Lozano) wrote…</i></summary><blockquote>

VABA *Protocol*
</blockquote></details>

Yeah, we should add to this for the VABA

**Comment by carrion256** [comment]
*[`protocol.md` line 147 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#-O5I2NNw5Zi1VGHKSS-G:-O5NSh2e4iJcrImaiTPf:bylo0gz) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L147)):*
<details><summary><i>Previously, palozano (Lozano) wrote…</i></summary><blockquote>

Is there something missing after the first `1:`?
</blockquote></details>

No, we're trying to imply 1: many here, should i be explicit?

**Review by carrion256 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Nuffle-Labs/docs/4)* status: 0 of 1 files reviewed, 22 unresolved discussions (waiting on @coderabbitai[bot], @firatsertgoz, and @palozano)

___
*[`protocol.md` line 10 at r1](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731435319:-O5NSAx749Hsp0bXP78M:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/67feda8e80c296891ab1fd1e60785a48faddf789/protocol.md#L10)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Fix typographical error.**

The term "pairing based" should be hyphenated as "pairing-based".

Apply this diff to fix the typographical error:

```diff
- this is an improved benefit over any pairing based signature.
+ this is an improved benefit over any pairing-based signature.
```



<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
- Adaptable Signatures: Since the protocol outputs Schnorr signatures, these can be adapted and cheaply verified without the need for any specific precompiles in the underlying chain, this is an improved benefit over any pairing-based signature.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[uncategorized] ~10-~10: This expression is usually spelled with a hyphen.
Context: ...n, this is an improved benefit over any pairing based signature. - Adaptively secure: HARTS r...

(BASED_HYPHEN)

</blockquote></details>
<details>
<summary>Markdownlint</summary><blockquote>

10-10: null
Lists should be surrounded by blank lines

(MD032, blanks-around-lists)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 17 at r1](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731435328:-O5NSOyNDysEATmLQlu9:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/67feda8e80c296891ab1fd1e60785a48faddf789/protocol.md#L17)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Add a comma.**

Consider adding a comma after "for now".

Apply this diff to add the comma:

```diff
- although for now we are going to use `secp256k1` as we build out the protocol
+ although, for now, we are going to use `secp256k1` as we build out the protocol
```



<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
> For the devnet, we have not yet decided on a curve for the signature, it would be useful to have a curve that is FFT-Friendly, although, for now, we are going to use `secp256k1` as we build out the protocol and decide on an FFT-Friendly curve when we introduce them. We can also explore EC-FFT.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[typographical] ~17-~17: Consider adding a comma here.
Context: ... a curve that is FFT-Friendly, although for now we are going to use `secp256k1` as we b...

(FOR_NOW_COMMA)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 25 at r1](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731435320:-O5NSQfF57zZ81wo7Zkx:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/67feda8e80c296891ab1fd1e60785a48faddf789/protocol.md#L25)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Add a comma and preposition.**

Consider adding a comma after "signature" and the preposition "to" before "all".

Apply this diff to fix the grammatical issue:

```diff
- schnorr signature, for this reason it is not compatible all underlying chains natively.
+ schnorr signature, for this reason, it is not compatible with all underlying chains natively.
```



<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
The signing protocol outputs a schnorr signature, for this reason, it is not compatible with all underlying chains natively.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[typographical] ~25-~25: It seems that a comma is missing.
Context: ...l outputs a schnorr signature, for this reason it is not compatible all underlying cha...

(FOR_THIS_REASON_COMMA)

---

[uncategorized] ~25-~25: Possible missing preposition found.
Context: ...e, for this reason it is not compatible all underlying chains natively.  Most chain...

(AI_HYDRA_LEO_MISSING_TO)

</blockquote></details>
<details>
<summary>Markdownlint</summary><blockquote>

25-25: Expected: 0 or 2; Actual: 1
Trailing spaces

(MD009, no-trailing-spaces)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 27 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731464947:-O5NSXmyE39A2XVviFJH:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L27)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Add a comma and fix article usage.**

Consider adding a comma after "this" and replacing "a" with "an".

Apply this diff to fix the grammatical issue:

```diff
- To address this we introduce a ERC-4337[^4337] aware adaptor contract
+ To address this, we introduce an ERC-4337[^4337] aware adaptor contract
```




<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
To address this, we introduce an ERC-4337[^4337] aware adaptor contract to the ethereum related chains. 
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[uncategorized] ~27-~27: Possible missing comma found.
Context: ...19 for signing transactions. To address this we introduce a ERC-4337[^4337] aware ad...

(AI_HYDRA_LEO_MISSING_COMMA)

---

[misspelling] ~27-~27: Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
Context: ...nsactions. To address this we introduce a ERC-4337[^4337] aware adaptor contract ...

(EN_A_VS_AN)

---

[uncategorized] ~27-~27: Do not mix variants of the same word (‘adaptor’ and ‘adapter’) within a single text.
Context: ...is we introduce a ERC-4337[^4337] aware adaptor contract to the ethereum related chains...

(EN_WORD_COHERENCY)

</blockquote></details>
<details>
<summary>Markdownlint</summary><blockquote>

27-27: Expected: 0 or 2; Actual: 1
Trailing spaces

(MD009, no-trailing-spaces)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 139 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731464950:-O5NSgNc8v__m0IScHIP:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L139)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Add a comma.**

Consider adding a comma after "set".

Apply this diff to add the comma:

```diff
- create an operator set or if the likeness properties allow, to append to an existing shard.
+ create an operator set, or if the likeness properties allow, to append to an existing shard.
```




<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
The properties of the application resolves them to a shard to either create an operator set, or if the likeness properties allow, to append to an existing shard. This allows operators to support applications in a capital efficient but fair way, as well as allowing applications which have similar properties to share the stake adaptively.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[uncategorized] ~139-~139: Possible missing comma found.
Context: ... shard to either create an operator set or if the likeness properties allow, to ap...

(AI_HYDRA_LEO_MISSING_COMMA)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 153 at r2](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1731464954:-O5NSpay2y5gPCVCfLOc:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/dc113e784137625bfce81595f379530c450e62b8/protocol.md#L153)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Add a comma.**

Consider adding a comma after "rules".

Apply this diff to add the comma:

```diff
- applying the validation rules. If they agree they will sign and broadcast their sharing.
+ applying the validation rules. If they agree, they will sign and broadcast their sharing.
```




<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
Upon share requests, the participants agree on the validity of the message by applying the validation rules. If they agree, they will sign and broadcast their sharing.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[uncategorized] ~153-~153: Possible missing comma found.
Context: ... applying the validation rules. If they agree they will sign and broadcast their shar...

(AI_HYDRA_LEO_MISSING_COMMA)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 25 at r3](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1734383719:-O5NSY2xAVj0dt_Q7sws:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/a562e631b9d77304f6365c678dc54d4c8825ad5a/protocol.md#L25)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Use "incompatible" to avoid wordiness.**

Consider using "incompatible" instead of "not compatible" for conciseness.

Apply this diff for conciseness:

```diff
- for this reason, it is not compatible with all underlying chains natively.
+ for this reason, it is incompatible with all underlying chains natively.
```



<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
The signing protocol outputs a schnorr signature, for this reason, it is incompatible with all underlying chains natively.
`````

</details>


<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[style] ~25-~25: Consider using “incompatible” to avoid wordiness.
Context: ...hnorr signature, for this reason, it is not compatible with all underlying chains natively. Mo...

(NOT_ABLE_PREMIUM)

</blockquote></details>

</details>


</blockquote></details>

Done.
___
*[`protocol.md` line 27 at r3](https://reviewable.io/reviews/Nuffle-Labs/docs/4#gh-1734383706:-O5NSYau818SLEwsjbjm:b-896fix) ([raw file](https://github.com/Nuffle-Labs/docs/blob/a562e631b9d77304f6365c678dc54d4c8825ad5a/protocol.md#L27)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

**Ensure consistent usage of "adapter".**

Do not mix variants of the same word ("adaptor" and "adapter") within a single text.

Apply this diff to ensure consistent usage:

```diff
- an ERC-4337[^4337] aware adaptor contract
+ an ERC-4337[^4337] aware adapter contract

- The Adaptor contract has the following responsibilities:
+ The Adapter contract has the following responsibilities:

- It is not decided whether the Adaptor contract should have a many-to-one relationship
+ It is not decided whether the Adapter contract should have a many-to-one relationship
```


Also applies to: 29-29, 37-37

<details>
<summary>Tools</summary>

<details>
<summary>LanguageTool</summary><blockquote>

[uncategorized] ~27-~27: Do not mix variants of the same word (‘adaptor’ and ‘adapter’) within a single text.
Context: ..., we introduce an ERC-4337[^4337] aware adaptor contract to the ethereum related chains...

(EN_WORD_COHERENCY)

</blockquote></details>
<details>
<summary>Markdownlint</summary><blockquote>

27-27: Expected: 0 or 2; Actual: 1
Trailing spaces

(MD009, no-trailing-spaces)

</blockquote></details>

</details>


</blockquote></details>

Done.

**Pull request merged**
